### ISSUE TITLE
یک پیشنهاد

### ISSUE THREAD

**Issue by WireKing** [ircfspace/fragment#6]
دوستان عزیز همه ما این مدت کانفیگ‌های VLESS زیادی رو روی Workers و  Pages کلادفلر ساختیم و دیدیم که در کنار امنیت خوبشون چقدر هم بدرد میخورن اما مع الاسف بیشتر ظرفیت اکانت‌هامون خالی مونده چون فوق فوقش از هر اکانت 10 یا 5 نفر دارن استفاده میکنن.

و حالا که مشکلات فرگمنت و کاستوم کانفیگ روی V2rayNG برطرف شدن و میشه برای کاستوم کانفیگ‌ها لینک سابسکرایب ساخت؛ به نظر من شما روی زیرساخت‌هاتون یه بخشی رو اضافه کنین تا بتونیم این کانفیگ‌های کلادفلر رو اهدا کنیم و زیر ساخت‌های شما تصادفی (مثلاً هر ده دقیقه یک بار) با هربار آپدیت لینک ساب یه کانفیگ تصادفی که فرگمنت هم روش فعال هست رو برامون بیاره و هر اکانتی هم که ظرفیت روزانه‌اش تکمیل شده میره استراحت میکنه و اکانت‌های خالی میاد جاش؛

اینجوری ماها که زیاد از بحث‌های خیلی تخصصی سردر نمیاریم، حداقل میتونیم به تعداد زیاد کانفیگ بسازیم و اونجا دونیت کنیم و به یه دردی بخوریم و صرفاً مصرف کننده محض نباشیم؛ و بقیه افراد هم که حداقل‌هارو هم نمیدونن، بتونن صرفاً با یک لینک ساب به اینترنت آزاد که حق همه است دسترسی کم دردسر تری داشته باشن.

در ضمن اگه این ایده به نظرتون خوب بود لطفاً کاری کنین که صرفاً کانفیگ‌های روی کلادفلر رو قبول کنه چون این مدت همه ما دیدیم که خیلی از کانفیگ‌ها امنیت کاربر براشون هیچ اهمیتی نداره و اغلب دنبال کارهایی غیر از کمک به مردم برای دسترسی آزاد به اینترنت هستن.

به امید روزهای بهتر برای همه

**Comment by ircfspace** [comment]
سلام
تشکر از پیشنهادتون
بررسی میکنمش

فقط این‌مورد رو درنظر داشته باشین که امکان اهدای کانفیگ (با بهره‌گیری از ظرفیت فرگمنت) در اپ مهسا وجود داره
https://play.google.com/store/apps/details?id=com.MahsaNet.MahsaNG

**Comment by WireKing** [comment]
بله در جریان هستم و کار این دوستان قابل تقدیر می‌باشد لیکن این کار بینظیر دوستان فعلاً فقط برای اندروید هستش، حالا من به شخصه به عنوان یک طرفدار پروپا قرص شما و با توجه به اندک دانسته‌هام فکر میکنم تیم شما و سایت شما میتونه یه راه‌حل جهان شمول بشه.

و این پیشنهاد بیشتر تمرکزش برای کانفیگ‌های ساخته شده روی Workers و Pages بود و این که مثلاً سیستمی باشه که خودش بالانس کنه کانفیگ‌هارو بین مصرف کننده‌ها و همه‌‌چیز مبتنی باشه بر کانفیگ‌های کلادفلر چون امنیت بی‌نظیری دارند؛

 و همچنین برای مثال در یک صفحه تعداد کانفیگ‌های اهدائی، تعداد کانفیگ‌های در حال کار، تعداد کانفیگ‌های تکمیل ظرفیت به صورت شفاف دیده بشه و اینطوری یه نوع فرهنگ مبتنی بر شفافیت رو هم گسترش میدید.

در واقع بیشتر پیشنهادم از برای این بود که همینطور که فرگمنت رو اضافه کردید و همه دامنه‌های فیلتر شده رو زنده کردید، شاید فردا یه راه‌حل دیگه‌ای پیدا بشه که کلی کیفیت و میزان دسترسی رو افزایش داد؛ شما با یک آپدیت همه کانفیگ‌های کلادفلر رو باهاش آداپته بکنید.

ببخشید که اطاله کلام شد و متشکرم که وقت میذارین.

**Comment by ircfspace** [comment]
تشکر از لطفی که داری؛ اما دانش و توانایی من متاسفانه محدوده و لازمه سایرین هم پیش‌قدم بشن.


البته در تکمیل بگم که همین‌داستان فرگمنت هم ایده GFW-knocker هست که هد پروژه مهساس.
روی نسخه‌های ویندوز و آی‌او‌اس هم داره برنامه‌ریزی میشه.
